
name: DevSecOps Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for SonarCloud to get full git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ============================================
      # SONARCLOUD SCAN
      # ============================================
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # ============================================
      # SECRETS SCAN
      # ============================================
      - name: Secrets Scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ============================================
      # DEPENDENCY SCAN
      # ============================================
      - name: Python Dependency Scan (Safety)
        run: |
          pip install safety
          safety check --json || true

      # ============================================
      # BUILD DOCKER IMAGE
      # ============================================
      - name: Build Docker Image
        run: |
          docker build -t devsecops-flask-project:${{ github.sha }} .

      # ============================================
      # CONTAINER IMAGE SCAN
      # ============================================
      - name: Container Image Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-flask-project:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      # ============================================
      # PUSH TO REGISTRY (only on main branch)
      # ============================================
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag devsecops-flask-project:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:latest
          docker tag devsecops-flask-project:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:latest
          docker push ghcr.io/${{ github.repository_owner }}/devsecops-flask-project:${{ github.sha }}

      # ============================================
      # DEPLOY
      # ============================================
      - name: Deploy (Placeholder)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Deployment would happen here"
          echo "All security scans passed successfully!"
